const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"帮助中心",
                        "menuJump":"列表",
                        "tableName":"chat"
                    }
                ],
                "menu":"帮助中心"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告资讯管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告资讯"
            }
			,
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"我的书架",
                        "menuJump":"列表",
                        "tableName":"shujia"
                    }
                ],
                "menu":"我的书架"
            }
			,
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"书城信息",
                        "menuJump":"列表",
                        "tableName":"xiaoshuo"
                    }
                ],
                "menu":"书城信息"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"作品收藏管理",
                        "menuJump":"列表",
                        "tableName":"xiaoshuoCollection"
                    }
                ],
                "menu":"我的作品收藏"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"作品评论信息",
                        "menuJump":"列表",
                        "tableName":"xiaoshuoLiuyan"
                    }
                ],
                "menu":"我的作品评论信息"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
